name: 'data_modeling'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'data_modeling'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


models:
  data_modeling:
    staging:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
vars:
  snapshot_date: '2025-12-31'
